apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: cerberus
  name: cerberus-serving-cert
spec:
  dnsNames:
    - cerberus.cerberus-operator-system.svc
    - cerberus.cerberus-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cerberus-selfsigned-issuer
  secretName: cerberus-server-cert
