# permissions for end users to edit accesstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: accesstoken-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cerberus
    app.kubernetes.io/part-of: cerberus
    app.kubernetes.io/managed-by: kustomize
  name: accesstoken-editor-role
rules:
- apiGroups:
  - cerberus.snappcloud.io
  resources:
  - accesstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cerberus.snappcloud.io
  resources:
  - accesstokens/status
  verbs:
  - get
