# permissions for end users to view webservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cerberus
    app.kubernetes.io/part-of: cerberus
    app.kubernetes.io/managed-by: kustomize
  name: webservice-viewer-role
rules:
- apiGroups:
  - cerberus.snappcloud.io
  resources:
  - webservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cerberus.snappcloud.io
  resources:
  - webservices/status
  verbs:
  - get
