apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cerberus
    app.kubernetes.io/instance: cerberus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: cerberus
    control-plane: controller-manager
  name: cerberus
spec:
  ports:
    - name: https
      port: 8082
      protocol: TCP
      targetPort: grpc
  selector:
    control-plane: controller-manager
  type: ClusterIP
