apiVersion: v1
kind: Secret
metadata:
  name: sample-access
  labels:
    cerberus.snappcloud.io/secret: "true"
data:
  token: c2FsYW1zYWxhbQo=
---
apiVersion: cerberus.snappcloud.io/v1alpha1
kind: AccessToken
metadata:
  labels:
    app.kubernetes.io/name: accesstoken
    app.kubernetes.io/instance: accesstoken-sample
    app.kubernetes.io/part-of: cerberus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cerberus
  name: accesstoken-sample
spec:
  active: Active
  secretRef:
    name: "sample-access"
