apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: cerberus-test-route
spec:
  ingressClassName: private
  routes:
    - conditions:
        - exact: /
      enableWebsockets: false
      permitInsecure: false
      services:
        - name: cerberus-echo
          port: 80
          weight: 100
      timeoutPolicy:
        idle: 5m
        idleConnection: 1h
        response: 30s
  virtualhost:
    fqdn: test.cerberus.snappcloud.io
    authorization:
      extensionRef:
        namespace: cerberus-system
        name: cerberus-cerberus-auth
      authPolicy:
        context:
          webservice: cerberus-webservice-sample
